# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Upgrades and New Features
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"