name: Publish to TestPyPI
on:
  push:
    branches:
      - main
  # release:
  #   types: [published]
permissions:
  id-token: write
  contents: read
jobs:
  PyTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          pip install --upgrade pytest
          python -m pytest -v
#   Publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Install Build Tools
#         run: |
#           pip install --upgrade build twine
#           pip install urllib3==1.26.15 --force-reinstall
#       - name: Publish Package
#         run: |
#           python -m build
#           echo "${{ secrets.testpypi_api_token }}"
#           twine upload -u __token__ -p ${{ secrets.testpypi_api_token }} --repository-url https://test.pypi.org/legacy/ dist/*
