name: Publish to Test PyPI
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Build Tools
        run: |
          pip install --upgrade build twine
          # pip install urllib3==1.26.15 --force-reinstall
      - name: Publish Package
        run: |
          python -m build
          twine upload -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }} --repository-url https://test.pypi.org/legacy/ dist/*
